services:
  aim-academy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aim-academy-frontend
    ports:
      - "9010:80"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
